apiVersion: v1
kind: Service
metadata:
  name: geo-dispatch-service
  namespace: geo-dispatch-prod
spec:
  selector:
    app: geo-dispatch-api
  ports:
    - protocol: TCP
      port: 80         # The port people hit from the outside
      targetPort: 3000 # The port your NestJS app is listening on
  type: LoadBalancer   # This tells Docker Desktop to give you a local URL